/*
 * generated by Xtext 2.27.0
 */
package chartIt.mydsl.ui.tests;

import chartIt.mydsl.ui.internal.MydslActivator;
import com.google.inject.Injector;
import org.eclipse.xtext.testing.IInjectorProvider;

public class MyDslUiInjectorProvider implements IInjectorProvider {

	@Override
	public Injector getInjector() {
		return MydslActivator.getInstance().getInjector("chartIt.mydsl.MyDsl");
	}

}
